---

parser: babel-eslint

globals:
  it: true
  expect: true
  describe: true
  test: true
  jest: true

extends:
- standard-react

plugins:
- react
- flowtype

rules:
  flowtype/require-valid-file-annotation: [2, "always"]
  flowtype/boolean-style: [2, "boolean"]
  flowtype/use-flow-type: 2
  no-unused-vars: [2, {vars: all, args: none}]
  jsx-quotes: [2, "prefer-double"]
  react/prop-types: [2, { skipUndeclared: true }]
  react/jsx-indent: 0 # handled by prettier
  react/jsx-indent-props: 0 # handled by prettier
